### ISSUE TITLE
GetAtt fails for container images.

### ISSUE THREAD

**Issue by OrEisenberg** [aws-cloudformation/aws-cloudformation-resource-providers-imagebuilder#3]
If you try to create an image using a ContainerRecipe, then trying to get the arn of the resulting output using GetAtt fails with error message 
```Unable to retrieve Name attribute for AWS::ImageBuilder::Image, with error message Resource of type 'AWS::ImageBuilder::Image' with identifier 'Not able to find the image id in current region.' was not found.```

It seems to me that this is because the arn is determined on the backend by referring to the `ImageId` attribute, which obviously doesn't exist for a container image, since it refers to the id of the AMI output by the Imagebuilder Image. 

See [this](https://github.com/aws/aws-cdk/issues/14588) relevant issue in the CDK project. 

On a related note, it would be very, very helpful to me if there could be an attribute associated with container Image objects corresponding to `ImageId` -- that is, if I could retrieve the container URI of the output container as an attribute of the Imagebuilder object. As it stands right now, the fact that I cannot do this effectively renders Cloudformation's Imagebuilder functionality ineffective for the management of containers. 

**EDIT**: Am I correct in saying that using `ContainerDistributionConfiguration` is not yet supported as well and that its reference in the docs was just due to an autogenerative process?

**Comment by wyuzheng** [comment]
We are releasing a new attribute `ImageUri` for container image.
`ContainerDistributionConfiguration` is already supported. All the fields/attributes name listed in the doc should be supported.

**Comment by OrEisenberg** [comment]
@wyuzheng 
That's terrific news! Thank for your willingness to implement this. I'm very much looking forward to scrapping our workaround!

**Comment by wyuzheng** [comment]
`ImageUri` had been added for `AWS::ImageBuilder::Image` resource if you are baking a Image with container recipe.
the usage is same as `ImageId`.

**Comment by wyuzheng** [comment]
Resolved with closure code: successful
